# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.IntegerField()),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(blank=True, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_municipio_tse', models.IntegerField()),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('faixa_etaria', models.CharField(blank=True, max_length=50, null=True)),
                ('grau_de_escolaridade', models.CharField(blank=True, max_length=50, null=True)),
                ('qtd_eleitores_no_perfil', models.IntegerField()),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='zona')),
            ],
        ),
    ]
