# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=50)),
                ('total_votos', models.IntegerField()),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='zona_voto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='eleitor',
            options={'verbose_name': 'eleitor', 'verbose_name_plural': 'eleitores'},
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='zona_eleitor'),
        ),
    ]
