# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161022_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='zona',
            field=models.IntegerField(unique=True),
        ),
    ]
